churchconnect-web/src/main/java/com/springthought/webapp/action/UserValueController.java
package com.springthought.webapp.action;

import com.springthought.Constants.UserValueType;
import com.springthought.model.UserValue;
import com.springthought.service.UserValueManager;
import com.springthought.util.FacesUtils;
import org.primefaces.component.datatable.DataTable;
import org.primefaces.event.RowEditEvent;
import org.primefaces.event.SelectEvent;
import org.primefaces.event.TabChangeEvent;
import org.primefaces.event.UnselectEvent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Component("userValueController")
@Scope("session")
public class UserValueController extends BasePage implements Serializable {

	private static final long serialVersionUID = 7939394506124504540L;
	private UserValueManager userValueManger = null;
	private List<UserValue> selectedUservalues = new ArrayList<UserValue>();
	private UserValue selectedUservalue = null;
	private List<UserValue> userValueList = null;
	private List<UserValue> contactLabelList = null;
	private UserValue selectedContactLabel = null;
	DataTable dataTable;
	private Boolean checked = false;
	private String postDeleteUpdate = "";


	@Autowired
	public void setUserValueManager(
			@Qualifier("userValueManager") UserValueManager manager) {
		this.userValueManger = manager;
	}

	public List<UserValue> getMemberTypes() {

		if (userValueList == null) {
			userValueList = this.userValueManger
					.getUserValueByType( UserValueType.CLASSIFICATION );
		}
		return userValueList;
	}

	/**
	 *
	 * @return
	 */
	public List<UserValue> getContactValues() {

		if (contactLabelList == null) {
			contactLabelList = this.userValueManger
					.getUserValueByType( UserValueType.CONTACT );
		}


		return contactLabelList;
	}

	public void onTabChange( TabChangeEvent event ){

		log.info("Tab = " + event.getTab().getTitle());

	}
	/**
	 * @return the selectedUservalues
	 */
	public List<UserValue> getSelectedUservalues() {
		return selectedUservalues;
	}

	/**
	 * @param selectedUservalues
	 *            the selectedUservalues to set
	 */
	public void setSelectedUservalues(List<UserValue> selectedUservalues) {
		this.selectedUservalues = selectedUservalues;
	}

	public void onEdit(RowEditEvent event) {

		UserValue uservalue = (UserValue) event.getObject();

		boolean isNew = (uservalue.getUservalueId() == null || uservalue
				.getUservalueId() == 0);

		userValueManger.save(uservalue);

		String key = (isNew) ? "userValueDetial.added" : "userValueDetial.updated";

		addMessage(key);

		selectedUservalue = null;
		checked = false;

	}

	public void onCancel(RowEditEvent event) {
		addMessage("errors.cancel");
		selectedUservalue = null;
		checked = false;
	}

	public void checkBoxSelect(SelectEvent event) {

		log.info("Number of items selected :=" + selectedUservalues.size());

	}

	public void checkBoxUnselect(UnselectEvent event) {

		log.info("Number of items selected :=" + selectedUservalues.size());

	}

	public void delete() {
/**
 		List<UserValue> values = selectedUservalues;

		for (UserValue uv : values) {
			userValueManger.remove(uv.getUservalueId());
		}

		selectedUservalues.removeAll(values);
		selectedUservalue = null;
		userValueList = null;
*
 */

		userValueManger.remove(selectedUservalue.getUservalueId());
		selectedUservalue = null;
		userValueList = null;
		checked = false;
		addMessage("userValueDetial.deleted");

	}

	public void addUserValueClassfication() {

		UserValue uv = new UserValue();

		uv.setValue_Type(UserValueType.CLASSIFICATION);
		uv.setName("[New classification]");
		uv.setDescr("[New description]");

		// should save row to the database and retrieve primary id from saved
		// recored.
		uv.setUservalueId(0L);
		userValueList.add(0, uv);
		selectedUservalues.add(uv);

		// dataTable.setRowIndex(dataTable.getRowCount());

		FacesUtils.addInfoMessage("Entry added");

	}

	/**
	 * @return the dataTable
	 */
	public DataTable getDataTable() {
		return dataTable;
	}

	/**
	 * @param dataTable
	 *            the dataTable to set
	 */
	public void setDataTable(DataTable dataTable) {
		this.dataTable = dataTable;
	}

	/**
	 * @return the checked
	 */
	public Boolean getChecked() {
		return this.checked;
	}

	/**
	 * @param checked
	 *            the checked to set
	 */
	public void setChecked(Boolean checked) {
		log.info("Checked value = " + checked.toString());
		this.checked = checked;
	}

	public void radioSelected(SelectEvent event) {
		checked = true;
	}

	/**
	 * @return the selectedUservalue
	 */
	public UserValue getSelectedUservalue() {
		return selectedUservalue;
	}

	/**
	 * @param selectedUservalue
	 *            the selectedUservalue to set
	 */
	public void setSelectedUservalue(UserValue selectedUservalue) {
		this.selectedUservalue = selectedUservalue;
	}

	/**
	 * @return the postDeleteUpdate
	 */
	public String getPostDeleteUpdate() {
		return postDeleteUpdate;
	}

	/**
	 * @param postDeleteUpdate the postDeleteUpdate to set
	 */
	public void setPostDeleteUpdate(String postDeleteUpdate) {
		this.postDeleteUpdate = postDeleteUpdate;
	}

	/**
	 * @return the selectedContactLabel
	 */
	public UserValue getSelectedContactLabel() {
		return selectedContactLabel;
	}

	/**
	 * @param selectedContactLabel the selectedContactLabel to set
	 */
	public void setSelectedContactLabel(UserValue selectedContactLabel) {
		this.selectedContactLabel = selectedContactLabel;
	}

	/**
	 * @return the contactLabelList
	 */
	public List<UserValue> getContactLabelList() {
		return contactLabelList;
	}

	/**
	 * @param contactLabelList the contactLabelList to set
	 */
	public void setContactLabelList(List<UserValue> contactLabelList) {
		this.contactLabelList = contactLabelList;
	}


}

churchconnect-web/src/main/webapp/sections/settings/contactType.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">



	<h:outputText
		value="#{text['userValueDetail.contactInformationLabels']}"
		style="font-weight:bold;text-decoration: underline;" />
	<p>
		<h:outputText
			value="Each individual may be assigned a classification  from the list of classification  defined here. These classifications are typically used to denote the status or state of the individual. For example: Member, Associate Member, and Regular Visitor." />
	</p>
	<p:panelGrid columns="2" styleClass="ui-panelgrid-blank">

		<p:commandButton id="cmdCntTypeDelete" icon="fa fa-trash Fs14 white" value="#{text['button.delete']}"
			styleClass="st-delete" oncomplete="PF('confirmation').show();"
			disabled="#{!userValueController.checked}"
			update=":dlgFrm:otplUserToDelete  :dlgFrm:cmdbtnConfirm">

			<f:setPropertyActionListener
				target="#{userValueController.postDeleteUpdate}"
				value=":mainFrm:acdnpnlSetting:dtContactLabel :mainFrm:growl" />

		</p:commandButton>



		<p:commandButton
			actionListener="#{userValueController.addUserValueClassfication}"
			id="cmdCntTypeAdd" icon="fa fa-plus Fs14 white" value="#{text['button.add']}"
			oncomplete="addRowOnComplete('.contact-datatable-data');"
			update=":mainFrm:acdnpnlSetting:dtContactLabel, :mainFrm:growl" />


	</p:panelGrid>

	<p:panelGrid columns="1" style="width:100%">



		<p:dataTable id="dtContactLabel" var="contactlabel"
			value="#{userValueController.contactValues}"
			rowKey="#{contactlabel.uservalueId}"
			selection="#{userValueController.selectedContactLabel}"
			editable="true" widgetVar="uvcntlbl" paginator="true"
			paginatorPosition="top" rows="10"
			paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink}
{LastPageLink} {RowsPerPageDropdown}"
			rowsPerPageTemplate="10,25,100" styleClass="contact-datatable-data">

			<p:ajax event="rowEdit" listener="#{userValueController.onEdit}"
				update=":mainFrm:growl :mainFrm:acdnpnlSetting:dtContactLabel :mainFrm:acdnpnlSetting:cmdCntTypeDelete"
				oncomplete="PF('uvcntlbl').unselectAllRows();" />

			<p:ajax event="rowEditCancel"
				listener="#{userValueController.onCancel}"
				update=":mainFrm:growl :mainFrm:acdnpnlSetting:cmdCntTypeDelete"
				oncomplete="PF('uvcntlbl').unselectAllRows();" />

			<p:ajax event="rowSelectRadio"
				listener="#{userValueController.radioSelected}"
				update=":mainFrm:acdnpnlSetting:cmdCntTypeDelete" />

			<p:column selectionMode="single" style="width:2%" />

			<p:column headerText="#{text['userValueDetail.contactType']}"
				style="width:40%">

				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{contactlabel.name}" />
					</f:facet>
					<f:facet name="input">
						<p:inputText id="txtName" value="#{contactlabel.name}">
							<f:validateRequired for="txtname" />

							<ui:remove>
								<f:validator validatorId="IsUniqueValue" />
								<f:attribute name="tablevalues"
									value="#{userValueController.contactlabels}" />
							</ui:remove>
						</p:inputText>
					</f:facet>`
				</p:cellEditor>

			</p:column>

			<p:column headerText="#{text['userValueDetial.description']}"
				style="width:40%">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{contactlabel.descr}" />
					</f:facet>
					<f:facet name="input">
						<h:inputText id="txtDescr" value="#{contactlabel.descr}" />
					</f:facet>
				</p:cellEditor>
			</p:column>

			<p:column headerText="#{text['userValueDetial.Actions']}"
				style="width:18%">
				<p:rowEditor />
			</p:column>

		</p:dataTable>


	</p:panelGrid>



</ui:composition>

churchconnect-web/src/main/webapp/sections/settings/dialog.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">


	<p:confirmDialog id="dialogConfirm"
		header="#{text['userValueDetail.deleteConfirmation']}"
		severity="alert" widgetVar="confirmation" showEffect="clip"
		hideEffect="fold">

		<f:facet name="message">

			<p:panelGrid columns="1">
				<h:outputFormat id="otplUserToDelete"
					value="#{text['userValueDetail.areYouSure']}">
					<f:param value="#{userValueController.selectedUservalue.name}" />
					<f:param value="#{text['userValueDetail.classification']}" />
				</h:outputFormat>
			</p:panelGrid>
		</f:facet>



		<p:commandButton id="cmdbtnConfirm" value="#{text['button.yes']}"
			oncomplete="PF('confirmation').hide()"
			actionListener="#{userValueController.delete}"
			update="#{userValueController.postDeleteUpdate}" />

		<p:commandButton id="decline" value="#{text['button.no']}"
			onclick="PF('confirmation').hide()" type="button" />


	</p:confirmDialog>



</ui:composition>

churchconnect-web/src/main/webapp/sections/settings/memberType.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">




	<h:outputText value="Individual Classification Codes"
		style="font-weight:bold;text-decoration: underline;" />
	<p>
		<h:outputText
			value="Each individual may be assigned a classification  from the list of classification  defined here. These classifications are typically used to denote the status or state of the individual. For example: Member, Associate Member, and Regular Visitor." />
	</p>
	
	<p:panelGrid columns="2"  styleClass="ui-panelgrid-blank">

		<p:commandButton id="cmdDelete" icon="fa fa-trash Fs14 white" value="#{text['button.delete']}"
			styleClass="st-delete" oncomplete="PF('confirmation').show();"
			disabled="#{!userValueController.checked}"
			update=":dlgFrm:otplUserToDelete  :dlgFrm:cmdbtnConfirm">

			<f:setPropertyActionListener
				target="#{userValueController.postDeleteUpdate}"
				value=":mainFrm:acdnpnlSetting:dtMemberType :mainFrm:growl" />

		</p:commandButton>

		<p:commandButton id="cmdAdd"
			actionListener="#{userValueController.addUserValueClassfication}"
			icon="fa fa-plus Fs14 white" value="#{text['button.add']}" oncomplete="addRowOnComplete('.member-datatable-data');" 
			update=":mainFrm:acdnpnlSetting:dtMemberType, :mainFrm:growl" /> 

	</p:panelGrid>

	<p:panelGrid columns="1" style="width:100%">

		<p:dataTable id="dtMemberType" var="membertype"
			value="#{userValueController.memberTypes}"
			rowKey="#{membertype.uservalueId}"
			selection="#{userValueController.selectedUservalue}" editable="true"
			widgetVar="uvdttble"
			paginator="true" paginatorPosition="top" rows="10"
			paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink}
{LastPageLink} {RowsPerPageDropdown}"
			rowsPerPageTemplate="10,25,100"
			styleClass="member-datatable-data">


			<p:ajax event="rowEdit" listener="#{userValueController.onEdit}"
				update=":mainFrm:growl :mainFrm:acdnpnlSetting:dtMemberType :mainFrm:acdnpnlSetting:cmdDelete"
				oncomplete="PF('uvdttble').unselectAllRows();" />


			<p:ajax event="rowEditCancel"
				listener="#{userValueController.onCancel}"
				update=":mainFrm:growl :mainFrm:acdnpnlSetting:cmdDelete"
				oncomplete="PF('uvdttble').unselectAllRows();" />

			<p:ajax event="rowSelectRadio"
				listener="#{userValueController.radioSelected}"
				update=":mainFrm:acdnpnlSetting:cmdDelete" />


			<p:column selectionMode="single" style="width:2%" />

			<p:column headerText="#{text['userValueDetail.classification']}"
				style="width:40%">

				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{membertype.name}" />
					</f:facet>
					<f:facet name="input">
						<p:inputText id="txtName" value="#{membertype.name}">
							<f:validateRequired for="txtname" />

							<ui:remove>
								<f:validator validatorId="IsUniqueValue" />
								<f:attribute name="tablevalues"
									value="#{userValueController.memberTypes}" />
							</ui:remove>
						</p:inputText>
					</f:facet>`
				</p:cellEditor>

			</p:column>

			<p:column headerText="#{text['userValueDetial.description']}"
				style="width:40%">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{membertype.descr}" />
					</f:facet>
					<f:facet name="input">
						<h:inputText id="txtDescr" value="#{membertype.descr}" />
					</f:facet>
				</p:cellEditor>
			</p:column>

			<p:column headerText="#{text['userValueDetial.Actions']}" style="width:18%">
				<p:rowEditor />
			</p:column>

		</p:dataTable>
	</p:panelGrid>



</ui:composition>